apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mnist-deployment
spec:
  selector:
    matchLabels:
      app: mnist
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mnist
    spec:
      containers:
      - name: mnist
        image: docker.io/kohlmann/experiments:2
        ports:
        - containerPort: 8501