apiVersion: v1
kind: Service
metadata:
  name: mnist
  annotations:
    metallb.universe.tf/address-pool: serving-ips
spec:
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: mnist
  type: LoadBalancer